name: build-K2P

on: 
  #push:
   # branches:
   # - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [K2P-USB]
        toolchain: [mipsel-linux-musl]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.target }}-${{ matrix.toolchain }}
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
          check-latest: true
          cache: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
      - name: Build
        run: |
          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.toolchain }}
          path: trunk/images/*.trx
